ConanFunTest: Upgrade dependencies of a test project
Upgrade the dependencies of the conanfile.txt test project. This
resolves a version conflict:

WARN: libcurl/7.79.1: requirement zlib/1.2.13 overridden by your conanfile to zlib/1.2.12
ERROR: Conflict in libxml2/2.9.14:
    'libxml2/2.9.14' requires 'zlib/1.2.13' while 'libcurl/7.79.1' requires 'zlib/1.2.12'.
    To fix this conflict you need to override the package 'zlib' in your root package.

Signed-off-by: Martin Nonnenmacher <martin.nonnenmacher@bosch.io>